name: Release

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ github.event.head_commit.message }}
        prerelease: ${{ contains(github.ref, 'RC') }}